name: similia_guide
description: A similia guide.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  sqflite: ^2.2.8+4
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
