name: similia_guide
description: A similia guide.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^10.1.2
  share_plus: ^7.2.1
  json_annotation: ^4.9.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.1

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf

  assets:
    - assets/images/
